USE [master]
GO

/****** Object:  Database [QLDongHo]    Script Date: 03/06/2021 10:30:06 SA ******/
CREATE DATABASE [QLDongHo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLDongHo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\QLDongHo.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QLDongHo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\QLDongHo_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QLDongHo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLDongHo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLDongHo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLDongHo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLDongHo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLDongHo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLDongHo] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLDongHo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QLDongHo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLDongHo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLDongHo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLDongHo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLDongHo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLDongHo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLDongHo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLDongHo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLDongHo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLDongHo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLDongHo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLDongHo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLDongHo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLDongHo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLDongHo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLDongHo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLDongHo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLDongHo] SET  MULTI_USER 
GO

ALTER DATABASE [QLDongHo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLDongHo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLDongHo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLDongHo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QLDongHo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLDongHo] SET QUERY_STORE = OFF
GO

USE [QLDongHo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [QLDongHo] SET  READ_WRITE 
GO

